# Generated by Django 5.2.5 on 2025-11-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='depense_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Dépense'),
        ),
    ]
