# Generated by Django 5.2.5 on 2025-12-13 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorieApp', '0002_initial'),
        ('depenseApp', '0002_depense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='categorieApp.categorie', verbose_name='Catégorie'),
        ),
    ]
