# Generated by Django 5.2.5 on 2025-12-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
