# Generated by Django 5.2.5 on 2025-11-28 18:54

import apps.objectifsEpargnesApp.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjEpargne',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Le nom doit contenir au moins 3 caractères.')])),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[apps.objectifsEpargnesApp.models.validate_positive_amount, django.core.validators.MaxValueValidator(1000000, message='Le montant ne peut pas dépasser 1 000 000.')])),
                ('target_date', models.DateField(blank=True, null=True, validators=[apps.objectifsEpargnesApp.models.validate_future_date])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACHIEVED', 'Achieved'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Objectif Epargne',
                'verbose_name_plural': 'Objectif Epargnes',
                'ordering': ['status', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='ObjEpargneContribution',
            fields=[
                ('cont_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[apps.objectifsEpargnesApp.models.validate_positive_amount])),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Objectif Epargne Contribution',
                'verbose_name_plural': 'Objectif Epargnes Contributions',
                'ordering': ['-added_at'],
            },
        ),
    ]
