# Generated by Django 5.2.5 on 2025-12-12 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detteApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dettes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rappel', models.DateTimeField()),
                ('actif', models.BooleanField(default=True)),
                ('envoye', models.BooleanField(default=False)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detteApp.debt')),
            ],
        ),
    ]
