# Generated by Django 5.2.5 on 2025-11-28 18:54

import apps.userApp.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom du groupe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('nb_membre', models.PositiveIntegerField(default=0, verbose_name='Nombre de membres')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='Veuillez entrer une adresse email valide')], verbose_name='Adresse email')),
                ('firstname', models.CharField(max_length=100, validators=[apps.userApp.models.validate_no_special_chars], verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=100, validators=[apps.userApp.models.validate_no_special_chars], verbose_name='Nom')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('utilisateur', 'Utilisateur')], default='utilisateur', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.appgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre de groupe',
                'verbose_name_plural': 'Membres de groupe',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='member_groups',
            field=models.ManyToManyField(blank=True, related_name='members', through='userApp.GroupMembre', to='userApp.appgroup', verbose_name='Groupes'),
        ),
    ]
