# Generated by Django 5.2.5 on 2025-12-01 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appgroup',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description du groupe'),
        ),
    ]
