# Generated by Django 5.2.5 on 2025-11-17 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom du groupe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('nb_membre', models.PositiveIntegerField(default=0, verbose_name='Nombre de membres')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.appgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre de groupe',
                'verbose_name_plural': 'Membres de groupe',
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='member_groups',
            field=models.ManyToManyField(blank=True, related_name='members', through='userApp.GroupMembre', to='userApp.appgroup', verbose_name='Groupes'),
        ),
    ]
