# Generated by Django 5.2.5 on 2025-12-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code de vérification'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de création du code'),
        ),
    ]
