# Generated by Django 5.2.5 on 2025-12-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_user_email_verification_code_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Le compte devient actif uniquement après vérification de l'email", verbose_name='Compte actif'),
        ),
    ]
